title: Gutemberg Rodrigues
description: Analista de Dados | Transformo dados em indicadores, dashboards e insights para apoiar decisões estratégicas.
url: "https://gutembergrodrigues.github.io"
baseurl: ""
